name: "Terraform Validate & Security"

on:
  # push:
  #   branches:
  #     - main
  #     - feat/*
  #     - fix/*
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  validate:
    name: "Validate, Lint & Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: "1.16.1"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef #v6.3.1
        with:
          tflint_version: "v0.55.0"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (Backend Disabled)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: |
          tflint --recursive -f compact || true
          tflint --recursive -f json > tflint-report.json || true

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf #v12.1347.0
        with:
          framework: terraform
          soft_fail: true
          output_format: cli
          config_file: .checkov.yml
